export const BEGIN_CLASS = 'CLASS/CLASS_BEGIN';

export const SET_IS_CLASS_BEGIN = 'SET_IS_CLASS_BEGIN';

export const SET_ROOM_STATUS = 'ROOM/SET_ROOM_STATUS';

export const SET_STUDENT_COUNT = 'ROOM/SET_STUDENT_COUNT';

export const SWITCH_LAYOUT = 'SWITCH_LAYOUT';

export const EXCHANGE_ONE2ONELAYOUT = 'EXCHANGE_ONE2ONELAYOUT';

export const INIT_CLASSROOM_STATE = 'INIT_CLASSROOM_STATE';

export const SET_PAGE_ORIENTATION = 'SET_PAGE_ORIENTATION';

export const SET_IS_ALL_NO_AUDIO = 'SET_IS_ALL_NO_AUDIO';

export const SET_IS_BIG_ROOM = 'SET_IS_BIG_ROOM';
export const SET_ROOM_INFO = 'SET_ROOM_INFO';
