export const clientEventKey = [
	'recv-chat-msg',
	'recv-pub-msg',
	'recv-del-msg',
	'signal-connected',
	'signal-reconnect',
	'signal-connection-state-change',
	'stream-volume-indicator',
	'stream-published',
	'stream-unpublished',
	'first-audio-frame-decode',
	'first-video-frame-decode',
	'stream-added',
	'stream-removed',
	'stream-reconnect-start',
	'stream-reconnect-end',
	'stream-subscribed',
	'injectstreamurl-state-change',
	'stream-network-quality',
	'mute-audio',
	'unmute-audio',
	'mute-video',
	'unmute-video',
	'channel-mode-change', // 通知 App 频道使用的模式改变
	'app-exception',
	'camera-device-changed',
	'microphone-device-changed',
	'speaker-device-changed',
	'peer-join',
	'peer-leave',
	'peer-evicted',
	'user-properties-update',
	'signal-connect-fail',
	'need-reload-page',
];

export const streamEventKey = [
	'recv-chat-msg',
	'recv-pub-msg',
];
